# Generated by Django 3.1.6 on 2021-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210213_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_link',
            name='collections',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
