# Generated by Django 3.1.6 on 2021-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_link_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_link',
            name='touxiang',
            field=models.ImageField(default='/media/touxiang/default.jpg', upload_to='touxiang', verbose_name='头像'),
        ),
    ]
