# Generated by Django 3.1.6 on 2021-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='电影名字')),
                ('actors', models.CharField(max_length=100, verbose_name='主要演员')),
                ('show_time', models.DateTimeField(verbose_name='上映时间')),
                ('director', models.CharField(max_length=20, verbose_name='导演')),
                ('type', models.CharField(choices=[('h', '动漫'), ('ke', '科幻'), ('xi', '喜剧'), ('a', '爱情'), ('d', '动作'), ('z', '战争'), ('x', '悬疑'), ('k', '恐怖'), ('w', '文艺'), ('o', '其他')], max_length=30, verbose_name='类型')),
                ('content', models.TextField(verbose_name='简介')),
                ('area', models.IntegerField(choices=[(1, '大陆'), (2, '香港'), (3, '中国台湾'), (4, '美国'), (5, '韩国'), (6, '日本'), (7, '欧洲'), (8, '法国')], verbose_name='地区')),
                ('image', models.ImageField(upload_to='media', verbose_name='封面')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
    ]
