# Generated by Django 3.1.6 on 2021-02-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210211_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.DateTimeField(verbose_name='上映时间'),
        ),
    ]
