# Generated by Django 3.1.6 on 2021-02-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210211_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.DateField(verbose_name='上映时间'),
        ),
    ]
