# Generated by Django 3.1.6 on 2021-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210212_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='area',
            field=models.IntegerField(choices=[(0, '全部'), (1, '大陆'), (2, '香港'), (3, '中国台湾'), (4, '美国'), (5, '韩国'), (6, '日本'), (7, '欧洲'), (8, '法国'), (9, '印度'), (10, '泰国'), (11, '英国')], verbose_name='地区'),
        ),
    ]
